/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RPSLS;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Toncic - luisalfredotoncic@gmail.com
 */
public class Ventana extends javax.swing.JFrame {

    //declaro Objetos Globales
    Humano jugador; 
    Maquina maquina;    
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        
        //seteo el texto del boton desafiar a 3 lineas y escribo su contenido
        String botonSheldon = "Desafiar\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a\nSheldon";
        btn_Desafiar.setText("<html>" + botonSheldon.replaceAll("\\n", "<br>") + "</html>");
        
        //instancio Objetos
        jugador = new Humano(0,lbl_Jugador1,"imagenes/jugador211x281.jpg");
        maquina = new Maquina(0,lbl_Jugador2,"imagenes/jugador2.png");
        
        //establezco parametros iniciales al abrir el juego 
        txt_Jug1.setText(String.valueOf(jugador.getContador()));
        txt_Jug2.setText(String.valueOf(maquina.getContador()));
        //Rad_Piedra.setSelected(true);        
        
        //seteo que no aparezca 2 opciones extras del easterEGG
        Panel_EasterEgg.setVisible(false);  
        btn_Desafiar.setVisible(false);
        //pack(); //permite redimensionar el panel al tamaño mas chico en timepo de ejecución ya que el panel esta oculto  
        //no parece andar el PACK ???????????????????
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Mano = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        Panel_Mano = new javax.swing.JPanel();
        Rad_Papel = new javax.swing.JRadioButton();
        Rad_Piedra = new javax.swing.JRadioButton();
        Rad_Tijera = new javax.swing.JRadioButton();
        Panel_EasterEgg = new javax.swing.JPanel();
        Rad_Lagarto = new javax.swing.JRadioButton();
        Rad_Spock = new javax.swing.JRadioButton();
        Panel_Marcador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Jug1 = new javax.swing.JTextField();
        txt_Jug2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbl_Jugador1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_Jugador2 = new javax.swing.JLabel();
        lbl_Ans = new javax.swing.JLabel();
        Panel_Botones = new javax.swing.JPanel();
        btn_Reglas = new javax.swing.JButton();
        btn_Jugar = new javax.swing.JButton();
        btn_Desafiar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Mano.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mano", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        buttonGroup_Mano.add(Rad_Papel);
        Rad_Papel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rad_Papel.setText("PAPEL");
        Rad_Papel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rad_PapelActionPerformed(evt);
            }
        });

        buttonGroup_Mano.add(Rad_Piedra);
        Rad_Piedra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rad_Piedra.setText("PIEDRA");
        Rad_Piedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rad_PiedraActionPerformed(evt);
            }
        });

        buttonGroup_Mano.add(Rad_Tijera);
        Rad_Tijera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rad_Tijera.setText("TIJERAS");
        Rad_Tijera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rad_TijeraActionPerformed(evt);
            }
        });

        buttonGroup_Mano.add(Rad_Lagarto);
        Rad_Lagarto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rad_Lagarto.setText("LAGARTO");
        Rad_Lagarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rad_LagartoActionPerformed(evt);
            }
        });

        buttonGroup_Mano.add(Rad_Spock);
        Rad_Spock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rad_Spock.setText("SPOCK");
        Rad_Spock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rad_SpockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_EasterEggLayout = new javax.swing.GroupLayout(Panel_EasterEgg);
        Panel_EasterEgg.setLayout(Panel_EasterEggLayout);
        Panel_EasterEggLayout.setHorizontalGroup(
            Panel_EasterEggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_EasterEggLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Rad_Lagarto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Rad_Spock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_EasterEggLayout.setVerticalGroup(
            Panel_EasterEggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_EasterEggLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Panel_EasterEggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rad_Lagarto)
                    .addComponent(Rad_Spock)))
        );

        javax.swing.GroupLayout Panel_ManoLayout = new javax.swing.GroupLayout(Panel_Mano);
        Panel_Mano.setLayout(Panel_ManoLayout);
        Panel_ManoLayout.setHorizontalGroup(
            Panel_ManoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ManoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_ManoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_ManoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Panel_EasterEgg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_ManoLayout.createSequentialGroup()
                        .addComponent(Rad_Papel)
                        .addGap(18, 18, 18)
                        .addComponent(Rad_Piedra)
                        .addGap(18, 18, 18)
                        .addComponent(Rad_Tijera)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_ManoLayout.setVerticalGroup(
            Panel_ManoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ManoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_ManoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rad_Papel)
                    .addComponent(Rad_Piedra)
                    .addComponent(Rad_Tijera))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(Panel_EasterEgg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(Panel_Mano, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 1, -1, -1));

        Panel_Marcador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marcador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("JUGADOR 1: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("JUGADOR 2: ");

        txt_Jug1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Jug1.setEnabled(false);

        txt_Jug2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Jug2.setEnabled(false);

        javax.swing.GroupLayout Panel_MarcadorLayout = new javax.swing.GroupLayout(Panel_Marcador);
        Panel_Marcador.setLayout(Panel_MarcadorLayout);
        Panel_MarcadorLayout.setHorizontalGroup(
            Panel_MarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MarcadorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Panel_MarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_MarcadorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Jug1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_MarcadorLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Jug2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Panel_MarcadorLayout.setVerticalGroup(
            Panel_MarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MarcadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_MarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Jug1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_MarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Jug2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(Panel_Marcador, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 1, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jugador 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 190, -1, 325));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jugador 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbl_Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 190, -1, -1));

        lbl_Ans.setFont(new java.awt.Font("Segoe UI", 0, 29)); // NOI18N
        lbl_Ans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lbl_Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 300, 40));

        Panel_Botones.setLayout(null);

        btn_Reglas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Reglas.setText("Reglas");
        btn_Reglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReglasActionPerformed(evt);
            }
        });
        Panel_Botones.add(btn_Reglas);
        btn_Reglas.setBounds(50, 10, 90, 32);

        btn_Jugar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Jugar.setText("Jugar");
        btn_Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_JugarActionPerformed(evt);
            }
        });
        Panel_Botones.add(btn_Jugar);
        btn_Jugar.setBounds(60, 50, 72, 32);

        btn_Desafiar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_Desafiar.setText("Desafiar ");
        btn_Desafiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DesafiarActionPerformed(evt);
            }
        });
        Panel_Botones.add(btn_Desafiar);
        btn_Desafiar.setBounds(40, 90, 110, 80);

        jPanel3.add(Panel_Botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 232, 170, 210));

        btn_Salir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 525, 63, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rad_PapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rad_PapelActionPerformed
//PAPEL        
        ImageIcon icon = new ImageIcon(getClass().getResource("imagenes/paper.png"));
        lbl_Jugador1.setIcon(icon);
        jugador.setEleccion(1);
    }//GEN-LAST:event_Rad_PapelActionPerformed

    private void Rad_PiedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rad_PiedraActionPerformed
//PIEDRA
        ImageIcon icon = new ImageIcon(getClass().getResource("imagenes/rock.png"));
        lbl_Jugador1.setIcon(icon);
        jugador.setEleccion(2);
    }//GEN-LAST:event_Rad_PiedraActionPerformed

    private void Rad_TijeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rad_TijeraActionPerformed
//TIJERAS
        ImageIcon icon = new ImageIcon(getClass().getResource("imagenes/scissors.png"));
        lbl_Jugador1.setIcon(icon);
        jugador.setEleccion(3);
    }//GEN-LAST:event_Rad_TijeraActionPerformed

    private void Rad_LagartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rad_LagartoActionPerformed
//LAGARTO
        ImageIcon icon = new ImageIcon(getClass().getResource("imagenes/lizard.png"));
        lbl_Jugador1.setIcon(icon);
        jugador.setEleccion(4);
    }//GEN-LAST:event_Rad_LagartoActionPerformed

    private void Rad_SpockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rad_SpockActionPerformed
//SPOCK
        ImageIcon icon = new ImageIcon(getClass().getResource("imagenes/spock.png"));
        lbl_Jugador1.setIcon(icon);
        jugador.setEleccion(5);
    }//GEN-LAST:event_Rad_SpockActionPerformed

    private void btn_ReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReglasActionPerformed
//REGLAS
        ImageIcon imagen;
        if(!(maquina.isEasterEgg())){  //dependiendo el modo de juego, selecciono una imagen de reglas o la otra
            
            imagen = new ImageIcon(getClass().getResource("imagenes/reglasEasy759x656.png"));            
        }else{
            imagen = new ImageIcon(getClass().getResource("imagenes/reglasHard759x656.png"));            
        }
        // Muestro el cuadro de diálogo con la imagen
        JOptionPane.showMessageDialog(null, "", "Imagen", JOptionPane.PLAIN_MESSAGE, imagen);
    }//GEN-LAST:event_btn_ReglasActionPerformed

    private void btn_JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_JugarActionPerformed
//JUGAR      
        if(jugador.getEleccion()!=0){ //valido que se haya marcado una opción para el jugador
                        
            maquina.jugar(); //se elije una opción al azar del jugador 2

            ImageIcon icon;
            switch(maquina.getEleccion()){
                case 1 -> {
                    icon = new ImageIcon(getClass().getResource("imagenes/paper.png"));
                    lbl_Jugador2.setIcon(icon);
                }
                case 2 -> {
                    icon = new ImageIcon(getClass().getResource("imagenes/rock.png"));
                    lbl_Jugador2.setIcon(icon);
                }
                case 3 -> {
                    icon = new ImageIcon(getClass().getResource("imagenes/Scissors.png"));
                    lbl_Jugador2.setIcon(icon);
                }
                case 4 -> {
                    icon = new ImageIcon(getClass().getResource("imagenes/lizard.png"));
                    lbl_Jugador2.setIcon(icon);
                }
                case 5 -> {
                    icon = new ImageIcon(getClass().getResource("imagenes/spock.png"));
                    lbl_Jugador2.setIcon(icon);
                }
            }
            //se decide quien gano, y se asigna el puntaje correspondiente         
            Arbitro.arbitrar(jugador, maquina, lbl_Ans); 
            
            //actualizo contadores en cajas de texto        
            txt_Jug1.setText(String.valueOf(jugador.getContador()));
            txt_Jug2.setText(String.valueOf(maquina.getContador()));
            
            //reviso condicion para activar modo secreto de juego
            if(((!maquina.isEasterEgg()) && (!maquina.isEasterEggChallenge()) ) && (jugador.getContador()-maquina.getContador())>=3){
                ImageIcon imagen = new ImageIcon(getClass().getResource("imagenes/sheldonAsk960x540.png"));            
                
                //pregunto si desea jugar el siguiente nivel
                int opc = JOptionPane.showOptionDialog(null, "", "Sheldon Cooper",
                           JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, imagen, null, null);

                //acato la opción
                if (opc == JOptionPane.OK_OPTION) {

                    maquina.setEasterEgg(true);
                    Panel_EasterEgg.setVisible(true);  
                    icon = new ImageIcon(getClass().getResource("imagenes/sheldonPlayer.png"));
                    lbl_Jugador2.setIcon(icon);
                    lbl_Ans.setText("Perderás!!");

                }else if (opc == JOptionPane.CANCEL_OPTION) { //correccion de sheldon siendo sheldon
                
                    btn_Desafiar.setVisible(true);
                    maquina.setEasterEggChallenge(true);   
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Elige una opción por favor", "¡Cuidado!",JOptionPane.WARNING_MESSAGE);        
        }
        if(jugador.getContador()-maquina.getContador() >=3){
            
            btn_Desafiar.setEnabled(true);
        }else{
            btn_Desafiar.setEnabled(false);
        }
    }//GEN-LAST:event_btn_JugarActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
//SALIR
        // vuelvo al jugador 1 a la posicion inicial sin nada seleccionado, y le devuelvo su avatar
        ImageIcon ico = new ImageIcon(getClass().getResource("imagenes/jugador211x281.jpg"));
        lbl_Jugador1.setIcon(ico);
        buttonGroup_Mano.clearSelection();
        jugador.setEleccion(0);
        
        //interaccion de sheldon con el jugador segun resultado en modo EASTER EGG
        if(maquina.isEasterEgg()){
            if(maquina.getContador()-jugador.getContador()>=0){

                ImageIcon icon = new ImageIcon(getClass().getResource("imagenes/sheldonWin.png"));
                lbl_Jugador2.setIcon(icon);
                lbl_Ans.setText("Perdedor...!!");
            }else{
                ImageIcon icon = new ImageIcon(getClass().getResource("imagenes/sheldonLose.png"));
                lbl_Jugador2.setIcon(icon);
                lbl_Ans.setText("Wheatooooon!!");
            }   
        }else{
            ImageIcon icon = new ImageIcon(getClass().getResource("imagenes/jugador2.png"));
            lbl_Jugador2.setIcon(icon);
            lbl_Ans.setText("Oh, ¡No te vayas!");
        }
        
        //pregunto si desea salir y guardo la opcion deseada
        int opc = JOptionPane.showOptionDialog(null, "¿Realmente desea salir del juego?", "Piedra Papel ó Tijeras",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        //acato la opción deseada
        if (opc == JOptionPane.OK_OPTION) {
            this.dispose(); //cierra el juego
        }else if (opc == JOptionPane.CANCEL_OPTION){
            if(maquina.isEasterEgg()){
            
                ImageIcon icon = new ImageIcon(getClass().getResource("imagenes/sheldonPlayer.png"));
                lbl_Jugador2.setIcon(icon);
                lbl_Ans.setText("Perderás!!");
            }else{
                ImageIcon icon = new ImageIcon(getClass().getResource("imagenes/jugador2.png"));
                lbl_Jugador2.setIcon(icon);
                lbl_Ans.setText("Iujuu!!, ¡Juguemos!");
            }
        }
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_DesafiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DesafiarActionPerformed

        maquina.setEasterEgg(true);
        Panel_EasterEgg.setVisible(true);  
        ImageIcon icon = new ImageIcon(getClass().getResource("imagenes/sheldonPlayer.png"));
        lbl_Jugador2.setIcon(icon);
        lbl_Ans.setText("Perderás!!");
        btn_Desafiar.setEnabled(false);
    }//GEN-LAST:event_btn_DesafiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Botones;
    private javax.swing.JPanel Panel_EasterEgg;
    private javax.swing.JPanel Panel_Mano;
    private javax.swing.JPanel Panel_Marcador;
    private javax.swing.JRadioButton Rad_Lagarto;
    private javax.swing.JRadioButton Rad_Papel;
    private javax.swing.JRadioButton Rad_Piedra;
    private javax.swing.JRadioButton Rad_Spock;
    private javax.swing.JRadioButton Rad_Tijera;
    private javax.swing.JButton btn_Desafiar;
    private javax.swing.JButton btn_Jugar;
    private javax.swing.JButton btn_Reglas;
    private javax.swing.JButton btn_Salir;
    private javax.swing.ButtonGroup buttonGroup_Mano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_Ans;
    private javax.swing.JLabel lbl_Jugador1;
    private javax.swing.JLabel lbl_Jugador2;
    private javax.swing.JTextField txt_Jug1;
    private javax.swing.JTextField txt_Jug2;
    // End of variables declaration//GEN-END:variables
}
